name: momo_flutter
description: A new Flutter project.

publish_to: 'none' 

version: 0.0.1+4

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  flutter_riverpod: ^1.0.0
  flutter_svg: ^1.0.0
  freezed_annotation: ^1.1.0
  json_annotation: ^4.4.0
  flutter_rating_bar: ^4.0.0
  retrofit: ^2.1.0
  dio: ^4.0.0
  intl: ^0.17.0
  infinite_scroll_pagination: ^3.1.0
  photo_manager: ^1.3.10
  pie_chart: ^5.1.0
  table_calendar: ^3.0.3
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  fluttertoast: ^8.0.8
  kakao_flutter_sdk_user: ^1.0.0
  cached_network_image: ^3.2.0
  device_info_plus: ^3.2.2
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  json_serializable:
  freezed:
  retrofit_generator:
  hive_generator: ^1.1.1
  flutter_native_splash: ^2.1.1

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/image/
    - assets/icon/
    - assets/icon/calendar/
    - assets/icon/category/
    - assets/icon/home/
    - assets/icon/meet/
    - assets/icon/mypage/
    - assets/icon/search/
    - assets/icon/tab/
    - assets/icon/onboarding/

  fonts:
    - family: NanumSquareOTF
      fonts:
        - asset: font/NanumSquareOTF/NanumSquareOTF_acB.otf
          weight: 700

        - asset: font/NanumSquareOTF/NanumSquareOTF_acR.otf
          weight: 400


flutter_native_splash:
  color: "#8a69f2"
  color_dark: "#8a69f2"
  image: assets/splash.png
  image_dark: assets/splash.png
  branding: assets/branding.png
  branding_dark: assets/branding.png
  branding_mode: bottom
  android_gravity: center
  android_12:
    image: assets/splash.png
    image_dark: assets/splash.png
    